# Generated by Django 3.1.14 on 2022-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20220726_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
